### PR TITLE
Configure travis settings

### PR DESCRIPTION
**Pull request by alanvelasques**
Test moodle 32 until moodle 37 with php 7.0 until php 7.2

### CODE REVIEW

**Comment by jfederico** [comment]
Why don you just use the script we have for the bigbluebuttonbn plugin? https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/blob/master/.travis.yml

**Comment by alanvelasques** [comment]
> Why don you just use the script we have for the bigbluebuttonbn plugin? https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/blob/master/.travis.yml
> 
> The other thing is that you test it first with your own travisCI account and once is ready open up the pull request. This is because this PR used blindside travisCI account and is holding other build unnecessarily.
> 
> And the other thing is that you don;t have to run all the build in development, you can comment out all except master or 3.7 and once it passes then start opening them in groups
> 
> 3.2 to 3.7 are kind of similar.
> 
> One last thing is that this blackboard script may not run with super old versions (before 3.0), this is because they are no longer suppoerted.

Thanks for the suggestions... I will use that in new PR.

**Comment by jfederico** [comment]
Yeah, the thing is that it should pass all the thest that were removed. And the plugin as it is works with Moodle 2.9 to present.

Thanks for the PR, but there is still plenty to be done (including the clean up)  in order to guaranty that the version works well in the newer versions of Moodle.

I am afraid that I will put this PR on hold until then.

**Comment by jfederico** [comment]
@alanvelasques I am closing this PR because I just added an script that actually works with Moodle  2.9 (as before) to 3.8. Also fixed the behat test. That is what the real work was.

Cheers

**Pull request closed without merging**
